### PR TITLE
Correct FLATCC_INSTALL_LIB bug

### PR DESCRIPTION
**Pull request by nebiun**
Replace lib with ${lib_dir} in compiler and runtime CMakeLists.

### CODE REVIEW

**Comment by mikkelfj** [comment]
Shouldn't this be `${dist_dir}/${lib_dir}` - see root CMakeLists

**Comment by nebiun** [comment]
No

**Comment by mikkelfj** [comment]
why?

**Comment by nebiun** [comment]
Original code use only 'lib' to define the destination directory, then full path is not required.
I replaced 'lib' with the variable that can contain 'lib' or 'lib64'.
No more, no less.

**Comment by mikkelfj** [comment]
I'm not sure the original code was correct - what happens if $dist_dir changes?

**Comment by nebiun** [comment]
dist_dir is set to ${PROJECT_SOURCE_DIR} and does not affect DESTDIR that is the "root" path for the installation.

**Comment by mikkelfj** [comment]
I see, so dist_dir is a bit misleading - probably from before install support was added to the project.

**Pull request merged**
