### PR TITLE
Added tests covering fixed bugs

### PR DESCRIPTION
**Pull request by skhoroshavin**
Added some tests to make sure that fixed bugs stay fixed :)

### CODE REVIEW

**Comment by mikkelfj** [comment]
Thanks - I didn't dare ask. Could you please rename TestIssue17 to something more telling. The test schema might also be used in other contexts and is loosely based on the flatc test schema.
    
    table TestIssue17

=>

    table TestJSONPrefixParsing

**Comment by skhoroshavin** [comment]
No problem, done.

**Comment by mikkelfj** [comment]
note that I squashed

**Comment by skhoroshavin** [comment]
Thanks. I was thinking about squashing commits myself and force pushing, but wasn't sure if this is handled correctly by github.

**Comment by mikkelfj** [comment]
I added some more test cases to cover the exact key length of 8, which was the reason for the original problem:
https://github.com/dvidelabs/flatcc/commit/78f35eff734d293e2e2ef2475a4ddc95c65b9eb4

**Comment by skhoroshavin** [comment]
Unfortunately there is a problem with your last commit - it no longer tests case when n != 8. You can check this by undoing my fix to parser generator and seeing that all tests pass. Or you can make a coverage report and see that this branch is no longer taken. Furthermore, I tried to undo your commit with additional test cases and checked coverage, and it shows that branch n == 8 is already taken by some other tests.

**Comment by mikkelfj** [comment]
Yes, I started wondering if this was the case myself.

**Comment by mikkelfj** [comment]
Reverted test case. BTW: github does support force commit but I used revert because this is on master branch

**Pull request merged**
