### PR TITLE
disable pedantic for GCC >= 8

### PR DESCRIPTION
**Pull request by le91688**
disable -pedantic flag for GCC version > 8

### CODE REVIEW

**Comment by mikkelfj** [comment]
No that is orthogonal.

You can probably make an if then else construct here:

https://github.com/dvidelabs/flatcc/blob/07ae7dca8118f9ab6d900a7d4797881cab708ba6/CMakeLists.txt#L211-L213

**Comment by pjr-z** [comment]
> No that is orthogonal.
> 
> You can probably make an if then else construct here:
> 
> https://github.com/dvidelabs/flatcc/blob/07ae7dca8118f9ab6d900a7d4797881cab708ba6/CMakeLists.txt#L211-L213

I thought the issue was happening with clang?

**Comment by le91688** [comment]
> No that is orthogonal.
> 
> You can probably make an if then else construct here:
> 
> https://github.com/dvidelabs/flatcc/blob/07ae7dca8118f9ab6d900a7d4797881cab708ba6/CMakeLists.txt#L211-L213

Ah my apologies, should have waited for your response in the issue thread!

Im happy to address the GCC version flag disable, but what i was hoping to accomplish was a generalized way to disable pedantic ( in my particular case, im struggling getting flatcc runtime to build for linux-arm / linux-mips with Clang )

**Comment by mikkelfj** [comment]
We could a add a FLATCC_ flag to disable pedantic. The problem is that every time there is a new GCC release, one or more users report some issue that is is a complete non-issue, and it needs to be investigated and GCC needs to be silenced. And with a flag, the user then needs to be told to add that flag to the build environment. GCC pendantic is just broken in my view.

**Comment by mikkelfj** [comment]
>  ( in my particular case, im struggling getting flatcc runtime to build for linux-arm / linux-mips with Clang )

Are you saying this a pedantic error raised by Clang?
In that case we need to fix the source of the problem in pattributes because we need clang pedantic since it usually find problematic areas. This is also why we can afford to remove on GCC.

**Comment by le91688** [comment]
> We could a add a FLATCC_ flag to disable pedantic. The problem is that every time there is a new GCC release, one or more users report some issue that is is a complete non-issue, and it needs to be investigated and GCC needs to be silenced. And with a flag, the user then needs to be told to add that flag to the build environment. GCC pendantic is just broken in my view.

Understood. How about a FLATCC_NOPEDANTIC flag, and we set that flag for GCC versions over a specified target?

**Comment by le91688** [comment]
> > ( in my particular case, im struggling getting flatcc runtime to build for linux-arm / linux-mips with Clang )
> 
> Are you saying this a pedantic error raised by Clang? In that case we need to fix the source of the problem in pattributes because we need clang pedantic since it usually find problematic areas. This is also why we can afford to remove on GCC.

Yes, thats correct, this is a clang error im experiencing with fall through.

**Comment by mikkelfj** [comment]
OK, lets take this dicussion back to the issue.

**Comment by le91688** [comment]
@mikkelfj  updated as per our discussion

**Review by mikkelfj — CHANGES_REQUESTED** [review]

**Comment by mikkelfj** [comment]
Can you test this with a few different GCC versions? The Travis build has stopped working so I don't have any insights on CI.

**Comment by le91688** [comment]
> Can you test this with a few different GCC versions? The Travis build has stopped working so I don't have any insights on CI.

sure, will test 8, 10, 11

**Comment by le91688** [comment]
@mikkelfj  , tested (via `rikorose/gcc-cmake` docker images) gcc 5 , gcc 8, and gcc 11 

command used:
`cmake -DFLATCC_INSTALL=on -DCMAKE_INSTALL_PREFIX="/test/" -DFLATCC_RTONLY=on -DCMAKE_BUILD_TYPE=Release && make install`

**Comment by mikkelfj** [comment]
Thanks. It would be better if you could run the full tests, or at least a build without RTONLY, see scripts/test.sh, but at least it shows the compilers don't go belly up.

**Comment by le91688** [comment]
> Thanks. It would be better if you could run the full tests, or at least a build without RTONLY, see scripts/test.sh, but at least it shows the compilers don't go belly up.

sure i can do that quick

**Review by mikkelfj — APPROVED** [review]

**Comment by le91688** [comment]
Tested with gcc 5 and gcc 11, running `scripts/test.sh` successfully

**Comment by mikkelfj** [comment]
Thanks, looks good!

**Comment by mikkelfj** [comment]
@pjr-z I missed your comment on clang, could have saved some effort, thanks for the heads up tho :)

**Pull request merged**
