### PR TITLE
_nest() was unnecessarily calling _buffer_start()/_buffer_end().

### PR DESCRIPTION
**Pull request by AndrewJDR**
This fixes an issue where an additional table root was inserted just prior
to a _nest()ed flatbuffer, which of course already has its own table root.

### CODE REVIEW

**Comment by AndrewJDR** [comment]
Attempt to fix issue #52

**Comment by AndrewJDR** [comment]
(Writing test for this currently, will commit it shortly)

**Comment by mikkelfj** [comment]
This is great work.

I wonder if the unwanted create buffer calls helped mask hide #51 where the vector length prefix.

A minor comment on coding style in monster_test.c (as always not arguing about what is right, just what is there):

NULL is tested using (!result) and names are not camelCased and no need to call the test nest_macro, just nest, since depending on view, everything or nothing are macros: nest is actually a function generated by a macro.

Good catch with updating reflection, but if you update this, the version should change in comments, hence the script:

reflection/generate_code.sh

But I tend to run this before releases are as a separate commit to reduce noise.

**Comment by AndrewJDR** [comment]
I think I integrated all of your feedback, let me know if you notice anything missing.
The binary format document was very helpful, I think it's the best reference available anywhere for the flatbuffer format and it helped me understand things well enough to catch this. So thanks again!

> I wonder if the unwanted create buffer calls helped mask #51 where the vector length prefix.

I'm a bit confused on this, how would this misbehavior in _nest() mask issue #51 which was related only to inline nesting? Does inline nesting ultimately use _nest() under the hood? (Doesn't seem to upon cursory glance)

**Comment by AndrewJDR** [comment]
Side note -- I just removed the reflection updates from my commit, so you can just handle that upon your next release whenever that might be.

**Comment by mikkelfj** [comment]
> I'm a bit confused on this, how would this misbehavior in _nest() mask issue #51 which was related only to inline nesting? Does inline nesting ultimately use _nest() under the hood? (Doesn't seem to upon cursory glance)

I'm not sure, just wondering. But I think it is more involved than that. Maybe the code just compiled unexpectedly early and I forgot to add tests.

**Pull request merged**
